qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 0
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 1
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 2
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 3
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 4
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 5
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 6
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 7
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 8
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 9
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 10
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 11
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 12
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 13
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 14
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 15
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 16
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 17
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 18
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 19
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 20
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 21
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 22
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 23
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 24
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 25
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 26
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 27
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 28
qsub -q hepshort.q subFitterToBatch.sh $PWD datafiles_training.dat 30 29

