#! /usr/bin/python
import os
import sys
import getopt
import time

#----------------------------------------------------------------------

def printHeader(file_out):
    print >> file_out,"# original version produced by " + os.path.basename(sys.argv[0]) + " on " + time.asctime()
    print >> file_out,"# command:"
    print >> file_out,"#   " + os.path.basename(sys.argv[0]) + " " + " ".join(sys.argv[1:])
    print >> file_out

#----------------------------------------------------------------------
# main
#----------------------------------------------------------------------

usage = """
job_maker [options]

--data/MC                          select data or MC
--AOD/RECO                         AOD should be standard
--caf                              send jobs using CAF (hadoop is std in SD)
--skim2pho                         skim on 2 photons
--noskim                           no skim performed (typically only for signal)
--storage=\"castor\" or \"hadoop\" use castor/hadoop as storage element
--name=                            name of the job, directory, files
--datasetpath=                     datasetpath
--runselection=                    comma separated list of runs
--events=                          number of events to process (-1 is standard)
--events_per_job=                  number of jobs per event (10000 is standard)
--json=""                          give the path of the json file to use (data only)
--lumis=                           equivalent to events in case of JSON file (it will be ignored if --json not set)
--lumis_per_job=                   equivalent to events_per_job in case of JSON file (it will be ignored if --json not set) 
--outputdir=                       output dir in the storage element (e.g. matteo/data/2010 in hadoop or /s/sani/data/2010  in castor)
--globaltag=                       change globaltag
--hlttag=                          set the HLT tag (HLT is standard, REGIGI3YX is frequent)
"""


# default selection
flagData = False
flagMC = False
flagSkimDiphoton = False
flagNoSkim = False
flagAOD = True

name = "NoNameGiven"
datasetpath=""
runselection = [""]
total_number = -1
events_job = 10000
storage = "hadoop"
email = ""
useCAF = False
user_remote_dir = ""
globaltag = ""
hlttag = ""
json = ""
lumis = -1
lumis_per_job=10

(opts, args) = getopt.getopt(sys.argv[1:], '', ['data', 'MC', 'AOD', 'RECO', 'skim2pho', 'storage=',  'name=', 'datasetpath=', 'outputdir=','runselection=', 'events=', 'events_per_job=', 'help', 'globaltag=', 'noskim', 'json=', 'lumis=', 'lumis_per_job=', 'caf','hlttag='])

for opt,argm in opts:
    if (opt == "--help"):
        print 'Usage: %s' % (usage)
        sys.exit(0)
    if (opt == "--data"):
        flagData = True
    elif (opt == "--MC"):
        flagMC = True
    elif (opt == "--AOD"):
        flagAOD = True
    elif (opt == "--RECO"):
        flagAOD = False
    elif (opt == "--caf"):
        useCAF = True
    elif (opt == "--skim2pho"):
        flagSkimDiphoton = True
    elif (opt == "--noskim"):
        flagNoSkim = True
    elif (opt == "--storage"):
        storage = argm
    elif (opt == "--name"):
        name = argm
    elif (opt == "--datasetpath"):
        datasetpath = argm
    elif (opt == "--runselection"):
        runselection = argm.split(",")
    elif (opt == "--events"):
        total_number = int(argm)
    elif (opt == "--events_per_job"):
        events_job = int(argm)
    elif (opt == "--outputdir"):
        user_remote_dir = argm
    elif (opt == "--globaltag"):
        globaltag = argm
    elif (opt == "--json"):
        json = argm
    elif (opt == "--lumis"):
        lumis = int(argm)
    elif (opt == "--lumis_per_job"):
        lumis_per_job = int(argm)
    elif (opt == "--hlttag"):
        hlttag = argm
    else:
        print 'Wrong options: %s' % (opt)
        sys.exit(3)

if (flagNoSkim is 'ON' and flagSkimDiphoton is 'ON') or (flagNoSkim is 'OFF' and flagSkimDiphoton is 'OFF'):
    print "You must have one and only one of these:"
    print "flagNoSkim is "+str(flagNoSkim)+"\tflagSkimdiphoton is "+str(flagSkimDiphoton)
    print "Try again when you have chosen one:  --skim2pho or --noskim."
    sys.exit(1)


for run in runselection:
    job_name = name
        
    file = open("template_aod_39X_cfg.py")
    lines = file.readlines()
    file.close()
    if os.path.exists("../test/crabTasks")==False:
        os.mkdir("../test/crabTasks")
    if os.path.exists("../test/crabTasks/"+job_name)==False:
        os.mkdir("../test/crabTasks/"+job_name)
    file_out = open("../test/crabTasks/" + job_name + "/" + job_name + "_cfg.py", "w")
    printHeader(file_out)

    for line in lines:
        if ("RootFileName" in line):
            file_out.write("process.h2ganalyzer.RootFileName = \'"+job_name+".root\'\n")
        elif ("flagData = 'OFF'" in line and flagData):
            file_out.write("flagData = \'ON\'\n")
        elif ("flagMC = 'OFF'" in line and flagMC):
            file_out.write("flagMC = \'ON\'\n")
        elif ("flagAOD = 'OFF'" in line and flagAOD):
            file_out.write("flagAOD = \'ON\'\n")
        elif ("flagAOD = 'ON'" in line and not flagAOD):
            file_out.write("flagAOD = \'OFF\'\n")
        elif ("flagNoSkim = 'OFF'" in line and flagNoSkim):
            file_out.write("flagNoSkim = \'ON\'\n")
        elif ("flagSkimDiphoton = 'OFF'" in line and flagSkimDiphoton):
            file_out.write("flagSkimDiphoton = \'ON\'\n")
        elif ("hltLabel = \"HLT\"" in line and hlttag != ""):
            file_out.write("hltLabel = \'"+hlttag+"\'\n")
        elif ("GlobalTag.globaltag" in line and globaltag != ""):
            file_out.write("process.GlobalTag.globaltag = \""+globaltag+"\"\n")
        else:
            file_out.write(line)
    file_out.close()

    
    # setup crab cfg file
    file = open("crab_template.cfg")
    lines = file.readlines()
    file.close()
    file_out = open("../test/crabTasks/" + job_name + "/crab_"+job_name+".cfg", "w")

    printHeader(file_out)

    for line in lines:
        if ("runselection" in line and flagData and run is not ""):
            file_out.write("runselection="+run+"\n")
        elif ("scheduler" in line and useCAF):
            file_out.write("scheduler = caf\n")
        elif ("datasetpath" in line):
            file_out.write("datasetpath="+datasetpath+"\n")
        elif ("pset" in line):
            file_out.write("pset = "+job_name+"_cfg.py\n")    
        elif ("output_file" in line):
            file_out.write("output_file = "+job_name+".root\n")
        elif ("working_dir" in line):
            file_out.write("ui_working_dir = " + os.getcwd()+"/../test/crabTasks/"+ job_name + "/"+ job_name + "\n")
        elif ("storage_element" in line and storage == "castor"):
            file_out.write("storage_element = srm-cms.cern.ch\n")
        elif ("storage_element" in line and useCAF):
            file_out.write("storage_element = T2_CH_CAF\n")
        elif ("storage_path" in line and storage == "castor"):
            file_out.write("storage_path = /srm/managerv2?SFN=/castor/cern.ch/user/\n")
        elif ("user_remote_dir" in line and storage == "castor"):
            file_out.write("user_remote_dir=/"+user_remote_dir+"/"+job_name +"\n")
        elif ("user_remote_dir" in line and useCAF):
            file_out.write("user_remote_dir=/"+job_name +"\n")
        elif ("storage_element" in line and storage == "hadoop"):
            file_out.write("storage_element = bsrm-1.t2.ucsd.edu\n")
        elif ("storage_path" in line and storage == "hadoop"):
            file_out.write("storage_path=/srm/v2/server?SFN=/hadoop/cms/store/user/\n")
        elif ("user_remote_dir" in line and storage == "hadoop"):
            file_out.write("user_remote_dir=/"+user_remote_dir+"/"+job_name+"\n")
        elif ("total_number_of_events" in line and json == ""):
            file_out.write("total_number_of_events = "+str(total_number)+"\n")
        elif ("events_per_job" in line and json == ""):
            file_out.write("events_per_job = "+str(events_job)+"\n")
        elif ("lumi_mask" in line and json != ""):
            file_out.write("lumi_mask = "+str(json)+"\n")
        elif ("lumis_per_job" in line and json != ""):
            file_out.write("lumis_per_job = "+str(lumis_per_job)+"\n")
        elif ("total_number_of_lumis" in line and json != ""):
            file_out.write("total_number_of_lumis = "+str(lumis)+"\n")
        else:
            file_out.write(line)
    file_out.close()
        

